apiVersion: apps/v1
kind: Deployment
metadata:
  name: globalvault-app-deployment
  labels:
    app: globalvault-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: globalvault-app
  template:
    metadata:
      labels:
        app: globalvault-app
    spec:
      containers:
      - name: globalvault-app
        image: krushit040/global-vault:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_DRIVER_NAME_VALUE
          valueFrom:
            configMapKeyRef:
              name: globalvault-db-config-map
              key: DB_DRIVER_NAME_VALUE
        - name: DB_HOST_SERVICE_NAME_VALUE
          valueFrom:
            configMapKeyRef:
              name: globalvault-db-config-map
              key: DB_HOST_SERVICE_NAME_VALUE
        - name: DB_SCHEMA_VALUE
          valueFrom:
            configMapKeyRef:
              name: globalvault-db-config-map
              key: DB_SCHEMA_VALUE
        - name: DB_PORT_VALUE
          valueFrom:
            configMapKeyRef:
              name: globalvault-db-config-map
              key: DB_PORT_VALUE
        - name: DB_USERNAME_VALUE
          valueFrom:
            secretKeyRef:
              name: globalvault-db-secret
              key: DB_USERNAME_VALUE
        - name: DB_PASSWORD_VALUE
          valueFrom:
            secretKeyRef:
              name: globalvault-db-secret
              key: DB_PASSWORD_VALUE
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: globalvault-db-config-map
              key: SERVER_PORT
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: globalvault-app-service
  labels:
    app: globalvault-app
spec:
  selector:
    app: globalvault-app
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: globalvault-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: globalvault-app-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 
...