apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: altus-db-pvc
spec:
  volumeName: altus-db-pv      
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 4Gi 