apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: globalvault-db-pvc
spec:
  volumeName: globalvault-db-pv      
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 4Gi 